import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const readSource = (path: string) => readFileSync(join(process.cwd(), path), 'utf8');

describe('UI CSS ownership', () => {
    it('keeps static widget styles in css files instead of React style tags', () => {
        const radioView = readSource('src/components/radio/RadioView.tsx');
        const toolbarView = readSource('src/components/toolbar/ToolbarView.tsx');
        const friendsBarView = readSource('src/components/friends/views/friends-bar/FriendsBarView.tsx');
        const wheelWinReveal = readSource('src/components/fortune-wheel/WheelWinReveal.tsx');
        const userIdentityView = readSource('src/common/UserIdentityView.tsx');
        const inventoryPrefixView = readSource('src/components/inventory/views/prefix/InventoryPrefixView.tsx');
        const bubbleHiddenView = readSource('src/components/nitrobubblehidden/NitrobubbleHiddenView.tsx');
        const prefixEffectsCss = readSource('src/css/common/PrefixEffects.css');
        const chatsCss = readSource('src/css/chat/Chats.css');

        expect(radioView).not.toContain('RADIO_STYLES');
        expect(toolbarView).not.toContain('TOOLBAR_STYLES');
        expect(toolbarView).not.toContain("backgroundPosition: '-25px -38px'");
        expect(toolbarView).toContain('tb-avatar-head');
        expect(friendsBarView).not.toContain('FRIENDBAR_STYLES');
        expect(wheelWinReveal).not.toContain('<style>');
        expect(userIdentityView).not.toContain('<style>');
        expect(inventoryPrefixView).not.toContain('<style>');
        expect(bubbleHiddenView).not.toContain('<style>');
        expect(bubbleHiddenView).not.toContain('dangerouslySetInnerHTML');
        expect(prefixEffectsCss).toContain('@keyframes prefix-pulse');
        expect(prefixEffectsCss).toContain('@keyframes prefix-sparkle');
        expect(chatsCss).toContain('.nitro-bubbles-hidden .newbubblehe');
    });

    it('keeps window-specific classes from repainting shared card chrome', () => {
        const groupCreatorView = readSource('src/components/groups/views/GroupCreatorView.tsx');
        const catalogView = readSource('src/components/catalog/CatalogView.tsx');
        const catalogAdminOfferEditView = readSource('src/components/catalog/views/admin/CatalogAdminOfferEditView.tsx');
        const catalogAdminPageEditView = readSource('src/components/catalog/views/admin/CatalogAdminPageEditView.tsx');
        const catalogAdminModalView = readSource('src/components/catalog/views/admin/CatalogAdminModalView.tsx');
        const catalogAdminQuickActionsView = readSource('src/components/catalog/views/admin/CatalogAdminQuickActionsView.tsx');
        const catalogLayoutDefaultView = readSource('src/components/catalog/views/page/layout/CatalogLayoutDefaultView.tsx');
        const catalogLayoutColorGroupingView = readSource('src/components/catalog/views/page/layout/CatalogLayoutColorGroupingView.tsx');
        const catalogLayoutSoundMachineView = readSource('src/components/catalog/views/page/layout/CatalogLayoutSoundMachineView.tsx');
        const catalogLayoutVipBuyView = readSource('src/components/catalog/views/page/layout/CatalogLayoutVipBuyView.tsx');
        const catalogLayoutMarketplaceItemView = readSource('src/components/catalog/views/page/layout/marketplace/CatalogLayoutMarketplaceItemView.tsx');
        const catalogLayoutPetView = readSource('src/components/catalog/views/page/layout/pets/CatalogLayoutPetView.tsx');
        const catalogLayoutTrophiesView = readSource('src/components/catalog/views/page/layout/CatalogLayoutTrophiesView.tsx');
        const getCatalogLayout = readSource('src/components/catalog/views/page/layout/GetCatalogLayout.tsx');
        const catalogCss = readSource('src/css/catalog/CatalogView.css');
        const inventoryCss = readSource('src/css/inventory/InventoryView.css');
        const friendsCss = readSource('src/css/friends/FriendsView.css');
        const roomSettingsCss = readSource('src/css/room/NavigatorRoomSettings.css');
        const roomWidgetsCss = readSource('src/css/room/RoomWidgets.css');
        const indexCss = readSource('src/css/index.css');
        const wiredCss = readSource('src/css/WiredView.css');
        const modToolsView = readSource('src/components/mod-tools/ModToolsView.tsx');
        const modToolsRoomView = readSource('src/components/mod-tools/views/room/ModToolsRoomView.tsx');
        const modToolsTicketsView = readSource('src/components/mod-tools/views/tickets/ModToolsTicketsView.tsx');
        const modToolsUserView = readSource('src/components/mod-tools/views/user/ModToolsUserView.tsx');
        const inventoryView = readSource('src/components/inventory/InventoryView.tsx');
        const inventoryCategoryFilterView = readSource('src/components/inventory/views/InventoryCategoryFilterView.tsx');
        const navigatorView = readSource('src/components/navigator/NavigatorView.tsx');
        const navigatorRoomSettingsView = readSource('src/components/navigator/views/room-settings/NavigatorRoomSettingsView.tsx');
        const wiredBaseView = readSource('src/components/wired/views/WiredBaseView.tsx');
        const friendsCategoryManagerView = readSource('src/components/friends/views/friends-list/FriendsCategoryManagerView.tsx');
        const friendsListView = readSource('src/components/friends/views/friends-list/FriendsListView.tsx');
        const friendsListRemoveConfirmationView = readSource('src/components/friends/views/friends-list/FriendsListRemoveConfirmationView.tsx');
        const friendsListRoomInviteView = readSource('src/components/friends/views/friends-list/FriendsListRoomInviteView.tsx');
        const friendsMessengerView = readSource('src/components/friends/views/messenger/FriendsMessengerView.tsx');
        const vaultView = readSource('src/components/vault/VaultView.tsx');
        const helpView = readSource('src/components/help/HelpView.tsx');
        const userSettingsView = readSource('src/components/user-settings/UserSettingsView.tsx');
        const chatHistoryView = readSource('src/components/chat-history/ChatHistoryView.tsx');
        const chatHistoryCss = readSource('src/css/chat/ChatHistoryView.css');
        const vaultCss = readSource('src/css/vault/VaultView.css');
        const userSettingsCss = readSource('src/css/user-settings/UserSettingsView.css');
        const sanctionStatusView = readSource('src/components/help/views/SanctionStatusView.tsx');
        const mentionsView = readSource('src/components/mentions/MentionsView.tsx');
        const translationSettingsView = readSource('src/components/translation/TranslationSettingsView.tsx');
        const userAccountSettingsView = readSource('src/components/user-settings/UserAccountSettingsView.tsx');
        const hcCenterView = readSource('src/components/hc-center/HcCenterView.tsx');
        const inventoryFurnitureDeleteView = readSource('src/components/inventory/views/furniture/InventoryFurnitureDeleteView.tsx');
        const badgeCreatorView = readSource('src/components/badge-creator/BadgeCreatorView.tsx');
        const badgeCreatorCss = readSource('src/css/badges/BadgeCreatorView.css');
        const chatWidgetWindowView = readSource('src/components/room/widgets/chat/ChatWidgetWindowView.tsx');
        const chooserWidgetView = readSource('src/components/room/widgets/choosers/ChooserWidgetView.tsx');
        const youtubePlayerView = readSource('src/components/toolbar/YouTubePlayerView.tsx');
        const infoStandUserView = readSource('src/components/room/widgets/avatar-info/infostand/InfoStandWidgetUserView.tsx');
        const infoStandFurniView = readSource('src/components/room/widgets/avatar-info/infostand/InfoStandWidgetFurniView.tsx');
        const infoStandBotView = readSource('src/components/room/widgets/avatar-info/infostand/InfoStandWidgetBotView.tsx');
        const infoStandRentableBotView = readSource('src/components/room/widgets/avatar-info/infostand/InfoStandWidgetRentableBotView.tsx');
        const infoStandPetView = readSource('src/components/room/widgets/avatar-info/infostand/InfoStandWidgetPetView.tsx');
        const infoStandCss = readSource('src/css/room/InfoStand.css');
        const chatInputView = readSource('src/components/room/widgets/chat-input/ChatInputView.tsx');
        const chatInputStyleSelectorView = readSource('src/components/room/widgets/chat-input/ChatInputStyleSelectorView.tsx');
        const chatWidgetWindowView2 = readSource('src/components/room/widgets/chat/ChatWidgetWindowView.tsx');

        expect(groupCreatorView).not.toContain('border border-[solid] border-[#283F5D]');
        expect(catalogView).not.toContain('habbo-swf-window');
        expect(catalogAdminModalView).toContain('createPortal');
        expect(catalogAdminModalView).toContain('nitro-card-shell');
        expect(catalogAdminModalView).toContain('fixed inset-0 z-[1000]');
        expect(catalogAdminModalView).toContain('max-w-[calc(100vw-16px)]');
        expect(catalogAdminModalView).toContain('max-h-[calc(100vh-16px)]');
        expect(catalogAdminModalView).toContain('overflow-y-auto');
        expect(catalogAdminOfferEditView).not.toContain('style={ { zIndex: 1000 } }');
        expect(catalogAdminOfferEditView).not.toContain('border-2 border-card-grid-item-border rounded px-2 py-1 bg-white');
        expect(catalogAdminOfferEditView).not.toContain('bg-white rounded border-2 border-card-grid-item-border p-2.5');
        expect(catalogAdminOfferEditView).toContain('nitro-catalog-admin-input');
        expect(catalogAdminOfferEditView).toContain('nitro-catalog-admin-panel');
        expect(catalogAdminOfferEditView).toContain('<CatalogAdminModalView');
        expect(catalogAdminOfferEditView).toContain('widthClassName="w-[420px]"');
        expect(catalogAdminQuickActionsView).toContain('setEditingPageData(true)');
        expect(catalogLayoutDefaultView).toContain('<CatalogAdminQuickActionsView');
        expect(catalogLayoutPetView).toContain('<CatalogAdminQuickActionsView');
        expect(catalogLayoutTrophiesView).toContain('<CatalogAdminQuickActionsView');
        expect(catalogLayoutColorGroupingView).not.toContain('style={ { maxHeight: 154 } }');
        expect(catalogLayoutSoundMachineView).not.toContain('style={ { height: 140 } }');
        expect(catalogLayoutVipBuyView).not.toContain("backgroundSize: 'contain'");
        expect(catalogLayoutMarketplaceItemView).not.toContain('style={ { width: 40, height: 40 } }');
        expect(catalogLayoutTrophiesView).not.toContain("boxShadow: '0 0 8px");
        expect(catalogLayoutTrophiesView).not.toContain('background: trophyText.length');
        expect(catalogLayoutTrophiesView).toContain('nitro-catalog-trophy-inscription');
        expect(catalogAdminPageEditView).toContain('<CatalogAdminModalView');
        expect(catalogAdminPageEditView).toContain('widthClassName="w-[520px]"');
        expect(catalogAdminPageEditView).not.toContain('border-2 border-card-grid-item-border rounded px-2 py-1 bg-white');
        expect(catalogAdminPageEditView).toContain('nitro-catalog-admin-input');
        expect(getCatalogLayout).not.toContain('custom_prefix');
        expect(getCatalogLayout).not.toContain('CatalogLayoutCustomPrefixView');
        expect(catalogCss).toContain('.nitro-catalog-window :where(.bg-white, .bg-gray-50, .bg-card-grid-item)');
        expect(catalogCss).toContain('.nitro-catalog-window :where(input, select, textarea)');
        expect(catalogCss).toContain('.nitro-catalog-window :where(.text-muted, .text-dark)');
        expect(catalogCss).toContain('.nitro-catalog-admin-body :where(.uppercase.font-bold)');
        expect(catalogCss).toContain('.nitro-catalog-admin-input');
        expect(catalogCss).toContain('.nitro-catalog-admin-button.is-primary');
        expect(catalogCss).toContain('.nitro-catalog-trophy-inscription.has-text');
        expect(catalogCss).toContain('.nitro-catalog-marketplace-item-icon');
        expect(catalogCss).toContain('.nitro-catalog-vip-hc-banner');
        expect(inventoryCategoryFilterView).not.toContain('style={ { width: currentTab === TAB_BADGES');
        expect(inventoryCategoryFilterView).toContain('nitro-inventory-filter-bar');
        expect(inventoryCss).toContain('.nitro-inventory-window .nitro-inventory-filter-bar.is-badges');
        expect(inventoryCss).toContain('.nitro-inventory-window :where(.bg-card-grid-item, .bg-white, .bg-light, .bg-muted)');
        expect(inventoryCss).toContain('.nitro-inventory-window :where(input, select, textarea)');
        expect(friendsCategoryManagerView).not.toContain('style={ { width: 270, minWidth: 270 } }');
        expect(friendsListRemoveConfirmationView).not.toContain('style={ { width: 270, height: 225');
        expect(friendsListRoomInviteView).not.toContain('style={ { width: 270, height: 225');
        expect(friendsCss).toContain('.nitro-friends-category-manager :where(input, select, textarea)');
        expect(friendsCss).toContain('width: min(270px, calc(100vw - 16px))');
        expect(roomSettingsCss).toContain('.nitro-room-settings');
        expect(roomSettingsCss).toContain(':where(input, select, textarea)');
        expect(indexCss).not.toContain(".nitro-wired :where(select, input[type='text'], input[type='number'], textarea)");
        expect(wiredCss).toContain(".nitro-wired :where(select, input[type='text'], input[type='number'], textarea)");
        expect(wiredCss).toContain('.nitro-wired__variable-picker-portal');
        expect(indexCss).toContain('.nitro-mod-tools :where(input, select, textarea)');
        expect(indexCss).toContain('[class*="nitro-mod-tools-"] :where(.bg-white, .bg-light, .bg-muted, .bg-card-grid-item, .bg-white\\/70)');
        expect(wiredCss).toContain('.nitro-wired__body');
        expect(wiredCss).toContain('overflow-y: auto');
        expect(modToolsView).toContain('max-w-[calc(100vw-16px)]');
        expect(modToolsRoomView).toContain('max-w-[calc(100vw-16px)]');
        expect(modToolsTicketsView).toContain('max-w-[calc(100vw-16px)]');
        expect(modToolsUserView).toContain('max-w-[calc(100vw-16px)]');
        expect(inventoryView).toContain('max-w-[calc(100vw-16px)]');
        expect(navigatorView).toContain('max-w-[calc(100vw-16px)]');
        expect(navigatorRoomSettingsView).toContain('max-w-[calc(100vw-16px)]');
        expect(wiredBaseView).toContain('max-h-[calc(100vh-16px)]');
        expect(friendsListView).toContain('max-w-[calc(100vw-16px)]');
        expect(friendsMessengerView).toContain('max-w-[calc(100vw-16px)]');
        expect(vaultView).toContain('max-w-[calc(100vw-16px)]');
        expect(helpView).toContain('max-w-[calc(100vw-16px)]');
        expect(userSettingsView).toContain('max-w-[calc(100vw-16px)]');
        expect(chatHistoryView).toContain('nitro-chat-history');
        expect(chatHistoryView).not.toContain("style={{ flex: 1, overflowY: 'auto'");
        expect(chatHistoryCss).toContain('.nitro-chat-history-scroll');
        expect(vaultCss).toContain('.nitro-vault-content');
        expect(userSettingsCss).toContain('.user-settings-window');
        expect(sanctionStatusView).toContain('max-w-[calc(100vw-16px)]');
        expect(mentionsView).toContain('max-w-[calc(100vw-16px)]');
        expect(translationSettingsView).toContain('max-w-[calc(100vw-16px)]');
        expect(userAccountSettingsView).toContain('max-w-[calc(100vw-16px)]');
        expect(hcCenterView).toContain('max-w-[calc(100vw-16px)]');
        expect(inventoryFurnitureDeleteView).toContain('max-w-[calc(100vw-16px)]');
        expect(badgeCreatorView).toContain('nitro-badge-creator');
        expect(badgeCreatorView).not.toContain('w-[760px] h-[680px]');
        expect(badgeCreatorView).not.toContain('style={{ minWidth: 220 }}');
        expect(badgeCreatorCss).toContain('.nitro-badge-creator');
        expect(badgeCreatorCss).toContain('width: min(760px, calc(var(--nitro-app-width, 100vw) - 16px))');
        expect(badgeCreatorCss).toContain('.badge-creator-main');
        expect(badgeCreatorCss).toContain('flex-direction: column');
        expect(chatWidgetWindowView).toContain('nitro-chat-widget-window');
        expect(chatWidgetWindowView).not.toContain('className="w-[460px] h-[240px]"');
        expect(chatWidgetWindowView).toContain('value={search}');
        expect(chooserWidgetView).toContain('nitro-chooser-widget');
        expect(chooserWidgetView).not.toContain('className="w-[420px] h-[400px]"');
        expect(youtubePlayerView).toContain('youtube-player-modal');
        expect(youtubePlayerView).toContain('is-fullscreen');
        expect(youtubePlayerView).not.toContain("'w-[550px]'");
        expect(youtubePlayerView).toContain('youtube-player-tabs');
        expect(youtubePlayerView).toContain('youtube-player-control-button');
        expect(youtubePlayerView).not.toContain('bg-amber-600 text-white');
        expect(roomWidgetsCss).toContain('.nitro-chooser-widget');
        expect(roomWidgetsCss).toContain('.nitro-chat-widget-window');
        expect(readSource('src/css/toolbar/ToolBar.css')).toContain('.youtube-player-modal.is-fullscreen');
        expect(readSource('src/css/toolbar/ToolBar.css')).toContain('.youtube-player-tab-button.is-active');
        expect(readSource('src/css/toolbar/ToolBar.css')).toContain('.youtube-player-empty-video');
        expect(infoStandUserView).toContain('infostand-shell');
        expect(infoStandUserView).toContain('infostand-panel');
        expect(infoStandUserView).not.toContain('bg-[rgba(28,28,32,0.95)]');
        expect(infoStandUserView).not.toContain("style={{ pointerEvents: 'auto', cursor: 'pointer' }}");
        expect(infoStandFurniView).toContain('infostand-shell');
        expect(infoStandFurniView).toContain('infostand-admin-button');
        expect(infoStandFurniView).not.toContain('bg-[rgba(28,28,32,.95)]');
        expect(infoStandFurniView).not.toContain("style={{ color: '#000' }}");
        expect(infoStandFurniView).not.toContain('bg-[#E55959]');
        expect(infoStandFurniView).not.toContain('bg-[#247FD1]');
        expect(infoStandBotView).toContain('infostand-shell');
        expect(infoStandBotView).not.toContain('nitro-infostand rounded');
        expect(infoStandRentableBotView).toContain('infostand-shell');
        expect(infoStandRentableBotView).not.toContain('container-fluid content-area');
        expect(infoStandPetView).toContain('infostand-shell');
        expect(infoStandPetView).not.toContain('nitro-infostand rounded');
        expect(infoStandCss).toContain('.infostand-panel.is-default');
        expect(infoStandCss).toContain('.infostand-buildtools-panel');
        expect(infoStandCss).toContain('.infostand-buildtools-move-button');
        expect(infoStandCss).toContain('.infostand-buildtools-height-button.is-down');
        expect(infoStandCss).toContain('.infostand-admin-button.is-primary');
        expect(chatInputView).toContain('nitro-chat-input-container');
        expect(chatInputView).not.toContain('rounded-[12px] border-2 border-black bg-[#dcdcdc]');
        expect(chatInputStyleSelectorView).toContain('nitro-chat-style-popover');
        expect(chatInputStyleSelectorView).not.toContain('bg-[#dfdfdf]');
        expect(chatInputStyleSelectorView).not.toContain("style={{ filter: 'none' }}");
        expect(chatWidgetWindowView2).toContain('nitro-chat-widget-content');
        expect(chatWidgetWindowView2).toContain('nitro-chat-widget-search');
        expect(chatWidgetWindowView2).not.toContain('bg-[#f2f2f2]');
        expect(roomWidgetsCss).toContain('.nitro-chat-style-trigger');
        expect(roomWidgetsCss).toContain('.nitro-chat-widget-color-strip');
    });
});
