export type ColorVariantType =
    | 'primary'
    | 'success'
    | 'danger'
    | 'secondary'
    | 'link'
    | 'black'
    | 'white'
    | 'dark'
    | 'warning'
    | 'muted'
    | 'light'
    | 'gray'
    | 'outline-primary'
    | 'outline-secondary'
    | 'outline-success'
    | 'outline-danger'
    | 'outline-warning';
